#!/bin/sh

set -e

if [ "$1" = "triggered" ]
then
    /usr/share/libphutil/scripts/phutil_rebuild_map.php --drop-cache /usr/share/arcanist/src/
    rm -f /usr/share/arcanist/src/.phutil_module_cache
    exit 0
fi

if [ "$1" = configure ]
then
    /usr/share/libphutil/scripts/phutil_rebuild_map.php --drop-cache /usr/share/arcanist/src/
    rm -f /usr/share/arcanist/src/.phutil_module_cache
fi

#DEBHELPER#
